import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="Ollivanders-Flask",
    version="1.0.0",
    author="JLDJR2481",
    author_email="jose.luis.de.jesus.ramon@gmail.com",
    description="FLASK API MONGO ATLAS",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/JLDJR2481/ollivanders-flask-api-rest",
    packages=setuptools.find_packages(),
    include_package_data=True,
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Apache License",
        "Operating System :: OS Independent",
    ],
    python_requires=">= 3.10",
    install_requires=[
        "aniso8601==9.0.1",
        "attrs==22.2.0",
        "bandit==1.7.5",
        "black==23.3.0",
        "cachetools==5.3.0",
        "chardet==5.1.0",
        "click==8.1.3",
        "colorama==0.4.6",
        "coverage==7.2.2",
        "distlib==0.3.6",
        "dnspython==2.3.0",
        "filelock==3.10.7",
        "flask==2.2.3",
        "flask-Cors==3.0.10",
        "flask-restful==0.3.9",
        "gitdb==4.0.10",
        "gitpython==3.1.31",
        "iniconfig==2.0.0",
        "itsdangerous==2.1.2",
        "jinja2==3.1.2",
        "markdown-it-py==2.2.0",
        "markupsafe==2.1.2",
        "mdurl==0.1.2",
        "mypy-extensions==1.0.0",
        "packaging==23.0",
        "pathspec==0.11.1",
        "pbr==5.11.1",
        "platformdirs==3.2.0",
        "pluggy==1.0.0",
        "pygments==2.14.0",
        "pymongo==4.3.3",
        "pyproject_api==1.5.1",
        "pytest==7.2.2",
        "python-dotenv==1.0.0",
        "pytz==2023.3",
        "pyyaml==6.0",
        "rich==13.3.3",
        "six==1.16.0",
        "snmap==5.0.0",
        "tox==4.4.8",
        "virtualenv==20.21.0",
        "werkzeug==2.2.3",
    ],
)
